tunnel: iahome-new
credentials-file: C:\Users\AAA\.cloudflared\4cc75dfd-fd02-4496-97f9-23f40fc1943d.json

ingress:
  - hostname: metube.iahome.fr
    service: http://192.168.1.150:8085  # Page d'authentification simple
  - hostname: iahome.fr
    service: http://192.168.1.150:3000
  - hostname: www.iahome.fr
    service: http://192.168.1.150:3000
  - hostname: qrcodes.iahome.fr
    service: http://192.168.1.150:7005
  - hostname: librespeed.iahome.fr
    service: http://192.168.1.150:8081
  - hostname: convert.iahome.fr
    service: http://192.168.1.150:8196
  - hostname: psitransfer.iahome.fr
    service: http://192.168.1.150:7009
  - service: http_status:404
