tunnel: b19084f4-e2d6-47f5-81c3-0972662e953c
credentials-file: C:\Users\AAA\.cloudflared\cert.pem

ingress:
  # Application principale IAHome
  - hostname: iahome.fr
    service: http://localhost:3000
  - hostname: www.iahome.fr
    service: http://localhost:3000
  
  # LibreSpeed via Traefik
  - hostname: librespeed.iahome.fr
    service: http://localhost:80
  
  # Services externes via Traefik
  - hostname: pdf.iahome.fr
    service: http://localhost:80
  - hostname: metube.iahome.fr
    service: http://localhost:80
  - hostname: psitransfer.iahome.fr
    service: http://localhost:80
  - hostname: qrcodes.iahome.fr
    service: http://localhost:80
  
  # Dashboard Traefik
  - hostname: traefik.iahome.fr
    service: http://localhost:8080
  
  # Catch-all rule
  - service: http_status:404