tunnel: iahome-new
credentials-file: C:\Users\AAA\.cloudflared\4cc75dfd-fd02-4496-97f9-23f40fc1943d.json

ingress:
  - hostname: iahome.fr
    service: https://192.168.1.150:443
    originRequest:
      httpHostHeader: iahome.fr
      noTLSVerify: true
  - hostname: www.iahome.fr
    service: https://192.168.1.150:443
    originRequest:
      httpHostHeader: www.iahome.fr
      noTLSVerify: true
  - hostname: metube.iahome.fr
    service: http://localhost:8081
  - hostname: librespeed.iahome.fr
    service: http://localhost:8085
  - hostname: whisper.iahome.fr
    service: http://localhost:8093
  - hostname: psitransfer.iahome.fr
    service: http://localhost:8087
  - hostname: qrcodes.iahome.fr
    service: http://localhost:7006
  - hostname: pdf.iahome.fr
    service: http://localhost:8086
  - hostname: converter.iahome.fr
    service: http://localhost:8096
  - hostname: stablediffusion.iahome.fr
    service: http://localhost:8085
  - hostname: ruinedfooocus.iahome.fr
    service: http://localhost:8087
  - hostname: comfyui.iahome.fr
    service: http://localhost:8088
  - hostname: sdnext.iahome.fr
    service: http://localhost:8089
  - hostname: invoke.iahome.fr
    service: http://localhost:8090
  - hostname: meeting-reports.iahome.fr
    service: http://localhost:3050
  - service: http_status:404
