tunnel: iahome-new
credentials-file: C:\Users\AAA\.cloudflared\02a960c5-edd6-4b3f-844f-410b16247262.json

ingress:
  - hostname: iahome.fr
    service: http://localhost:3000
    originRequest:
      httpHostHeader: iahome.fr
      noTLSVerify: true
      disableChunkedEncoding: true
      connectTimeout: 30s
      tlsTimeout: 10s
      tcpKeepAlive: 30s
      keepAliveConnections: 10
      keepAliveTimeout: 1m30s
  - hostname: www.iahome.fr
    service: http://localhost:3000
    originRequest:
      httpHostHeader: www.iahome.fr
      noTLSVerify: true
      disableChunkedEncoding: true
      connectTimeout: 30s
      tlsTimeout: 10s
      tcpKeepAlive: 30s
      keepAliveConnections: 10
      keepAliveTimeout: 1m30s
  - hostname: metube.iahome.fr
    service: http://localhost:8081
    originRequest:
      httpHostHeader: metube.iahome.fr
      noTLSVerify: true
  - hostname: librespeed.iahome.fr
    service: http://localhost:8085
    originRequest:
      httpHostHeader: librespeed.iahome.fr
      noTLSVerify: true
  - hostname: whisper.iahome.fr
    service: http://localhost:8093
    originRequest:
      httpHostHeader: whisper.iahome.fr
      noTLSVerify: true
  - hostname: psitransfer.iahome.fr
    service: http://localhost:8087
    originRequest:
      httpHostHeader: psitransfer.iahome.fr
      noTLSVerify: true
  - hostname: qrcodes.iahome.fr
    service: http://localhost:7006
    originRequest:
      httpHostHeader: qrcodes.iahome.fr
      noTLSVerify: true
  - hostname: pdf.iahome.fr
    service: http://localhost:8086
    originRequest:
      httpHostHeader: pdf.iahome.fr
      noTLSVerify: true
  - hostname: stablediffusion.iahome.fr
    service: http://192.168.1.150:7880
    originRequest:
      httpHostHeader: stablediffusion.iahome.fr
      noTLSVerify: true
  - hostname: comfyui.iahome.fr
    service: http://192.168.1.150:8188
    originRequest:
      httpHostHeader: comfyui.iahome.fr
      noTLSVerify: true
  - hostname: meeting-reports.iahome.fr
    service: http://127.0.0.1:3050
    originRequest:
      httpHostHeader: meeting-reports.iahome.fr
      noTLSVerify: true
      disableChunkedEncoding: true
      connectTimeout: 30s
      tlsTimeout: 10s
  - service: http_status:404
