services:
  librespeed:
    image: adolfintel/speedtest:latest
    container_name: librespeed-prod
    restart: unless-stopped
    ports:
      - "8085:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./data:/config
    networks:
      - iahome-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=iahome-network"
      - "traefik.http.routers.librespeed.rule=Host(`librespeed.iahome.fr`)"
      - "traefik.http.routers.librespeed.entrypoints=websecure"
      - "traefik.http.routers.librespeed.tls.certresolver=letsencrypt"
      - "traefik.http.services.librespeed.loadbalancer.server.port=80"

networks:
  iahome-network:
    external: true
